spring.application.name=trainy

#MySQL config
spring.datasource.url=${DB_DATABASE}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

#Hibernate config (hibernate = ORM tool)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

#Timezone config - display times in Swedish timezone
spring.jackson.time-zone=Europe/Stockholm
