// Trafikverket location signature → full name
export const STATION_NAMES = {
  'Cst': 'Stockholm Central',
  'Flb': 'Flemingsberg',
  'Tul': 'Tulinge',
  'Söc': 'Södertälje C',
  'Söm': 'Södertälje Syd',
  'Gn': 'Gnesta',
  'Vhd': 'Vagnhärad',
  'Nk': 'Nyköping C',
  'Nr': 'Norrköping C',
  'L': 'Linköping C',
  'Kbf': 'Katrineholm C',
  'Hpbg': 'Hallsberg',
  'Or': 'Örebro C',
  'Kvb': 'Köping',
  'Kob': 'Kolbäck',
  'Tbe': 'Tillberga',
  'Vs': 'Västerås C',
  'En': 'Enköping',
  'Bls': 'Bålsta',
  'Bkb': 'Bro',
  'Khä': 'Kallhäll',
  'Jkb': 'Jakobsberg',
  'Bkn': 'Barkarby',
  'Spå': 'Spånga',
  'U': 'Uppsala C',
  'Ups': 'Uppsala C',
  'Krn': 'Knivsta',
  'Märsta': 'Märsta',
  'Mä': 'Märsta',
  'Äs': 'Älvsjö',
  'Åbe': 'Åby',
  'Esn': 'Eskilstuna C',
  'Eskn': 'Eskilstuna C',
  'Sal': 'Sala',
  'Skp': 'Skövde C',
}

// All main Mälartåg stations shown in the selector
export const MALARTAG_STATIONS = [
  { code: 'Cst', name: 'Stockholm Central' },
  { code: 'Äs', name: 'Älvsjö' },
  { code: 'Flb', name: 'Flemingsberg' },
  { code: 'Tul', name: 'Tulinge' },
  { code: 'Söc', name: 'Södertälje C' },
  { code: 'Gn', name: 'Gnesta' },
  { code: 'Vhd', name: 'Vagnhärad' },
  { code: 'Nk', name: 'Nyköping C' },
  { code: 'Nr', name: 'Norrköping C' },
  { code: 'Kbf', name: 'Katrineholm C' },
  { code: 'Hpbg', name: 'Hallsberg' },
  { code: 'Or', name: 'Örebro C' },
  { code: 'Vs', name: 'Västerås C' },
  { code: 'Tbe', name: 'Tillberga' },
  { code: 'En', name: 'Enköping' },
  { code: 'Bls', name: 'Bålsta' },
  { code: 'U', name: 'Uppsala C' },
  { code: 'Sal', name: 'Sala' },
  { code: 'Esn', name: 'Eskilstuna C' },
  { code: 'Kob', name: 'Kolbäck' },
  { code: 'Kvb', name: 'Köping' },
]

export function getStationName(code) {
  return STATION_NAMES[code] ?? code
}
